# Задачи!

## Найти в массиве те элементы, значение которых меньше среднего арифметического, взятого от всех элементов массива.

In [ ]:
# используйте случайный двумерный массив:
A = np.random.randint(-5, 10, size=(np.random.randint(2,5), np.random.randint(3,10)))
A

array([[ 4, -2,  2,  7,  6,  4,  6],
       [ 9,  8,  9,  6,  8, -2, -3],
       [-4,  7,  6,  7, -1, -5, -2]])

In [ ]:
[item for item in A.flatten() if item < A.mean()]

[-2, 2, -2, -3, -4, -1, -5, -2]

## Вычислить сумму модулей элементов массива, расположенных после первого отрицательного элемента.
Массив - двумерный.

In [ ]:
# используйте случайный двумерный массив:
A = np.random.randint(-5, 10, size=(np.random.randint(2,5), np.random.randint(3,10)))
A

array([[ 6, -2, -5],
       [-2,  8,  5],
       [ 6,  5, -5],
       [ 5,  3,  2]])

In [ ]:
for i in range(len(A.flatten())):
  if A.flatten()[i] < 0:
    neg_index = i
    break
neg_index

1

In [ ]:
sum(abs(A.flatten()[neg_index+1::]))

46

## Во втором массиве сохранить индексы четных элементов первого массива. 
Например, если дан массив со значениями 8, 3, 15, 6, 4, 2, то во второй массив надо заполнить значениями 1, 4, 5, 6 (или 0, 3, 4, 5 - если индексация начинается с нуля), т.к. именно в этих позициях первого массива стоят четные числа.

In [ ]:
#  используйте массив В
B = np.random.randint(1, 100, size=(np.random.randint(1,20),))
B

array([56, 36, 56, 11, 87, 65, 35, 37, 75, 47, 40, 49, 50])

In [ ]:
[i for i in range(len(B.flatten())) if B.flatten()[i]%2==0]

[0, 1, 2, 10, 12]

## Отсортировать массив, заполненный случайными числами, по возрастанию. 
Вывести на экран массив в исходном и отсортированном виде.

In [ ]:
#  используйте массив В
B = np.random.randint(-100, 100, size=(np.random.randint(10,40),))
B

array([-71, -53, -97,  20,  -7, -36,  74,  54,  19,   4,  12, -24,  14,
       -70,  24, -14, -46, -63,  86,  94, -68, -89, -58, -54,  66,   6,
       -70,   1, -40,  23, -95,  42, -51, -39, -62,  57])

In [ ]:
sorted(B)

[-97,
 -95,
 -89,
 -71,
 -70,
 -70,
 -68,
 -63,
 -62,
 -58,
 -54,
 -53,
 -51,
 -46,
 -40,
 -39,
 -36,
 -24,
 -14,
 -7,
 1,
 4,
 6,
 12,
 14,
 19,
 20,
 23,
 24,
 42,
 54,
 57,
 66,
 74,
 86,
 94]

## Найдите сумму положительных элементов главной диагонали матрицы.


In [ ]:
# Ипользуйте массив:
A = np.random.randint(-5, 10, size=(np.random.randint(3,10),np.random.randint(3,10)))
A

array([[-3, -4, -1,  0, -1,  1,  0,  9,  4],
       [ 3, -3,  0, -5,  7,  3, -4,  5, -2],
       [-3, -1, -2,  8,  9, -4,  9,  1,  8],
       [ 2,  9,  3,  0, -4,  8,  7, -1, -5],
       [ 0,  6,  6,  6,  1, -3,  1, -3, -5],
       [ 8,  7, -4,  3,  6, -4, -4, -4,  6],
       [ 4, -5, -4,  6,  1,  8,  1, -2,  6]])

In [ ]:
sum([item for item in np.diagonal(A) if item > 0])

2

## Проверьте, что два вектора одинаковые по набору элементов и количеству. 

Например [1,2,2,3] == [3,2,2,1]

In [ ]:
#  используйте массивы:
B = np.random.randint(-100, 100, size=(np.random.randint(1,10),))
C = np.random.randint(-100, 100, size=(np.random.randint(1,10),))
B, C

(array([45]), array([-6,  1]))

In [ ]:
B.sort()
C.sort()

np.array_equal(B,C)

False

## Найди минимальное значение перед которым стоит 0 в массиве.

In [ ]:
#  используйте массив:
B = np.random.randint(-10, 10, size=(np.random.randint(1,10),))
B

array([ 0,  4,  0, -5, -5, -7, -1,  7])

In [ ]:
min = B.max()+1

for i in range(1, len(B)):
  if B[i-1]==0 and B[i]<min:
    min=B[i]

if min == B.max()+1:
  print("Нулей в массиве нет")
else:
  print(min)

-5


## А вот и сложное задание. 

Пусть вам дан массив [1,2,2,2,3]. Вам нужно вернуть ([1,2,3],[1,3,1])

Это что-то вроде словаря подсчёта. В первом массиве элементы, во втором - их количество.


In [ ]:
#  используйте массив:
B = np.random.randint(1, 10, size=(np.random.randint(1,20),))
B

array([7, 6, 9, 6, 3, 4, 9, 9, 4, 2, 6, 5, 3, 9, 5])

In [ ]:
from collections import Counter

(list(Counter(B).keys()), list(Counter(B).values()))

([7, 6, 9, 3, 4, 2, 5], [1, 3, 4, 2, 2, 1, 2])

## Ну и на закуску. 
Вычислите  евклидовое расстояние между двумя векторами объектов.

In [ ]:
#  используйте массивы:
k = np.random.randint(1,10)
B = np.random.randint(-100, 100, size=(k,))
C = np.random.randint(-100, 100, size=(k,))
B, C

(array([ 92, -59, -23,  83, -31, -55,  95,  72,  63]),
 array([ 69, -58, -25, -21,  68, -87, -13, -57, -24]))

In [ ]:
np.linalg.norm(B-C)

240.9336008115099